### ISSUE TITLE
How to collaborate?

### ISSUE THREAD

**Issue by lucafregoso** [BKWLD/decoy#10]
Are you using any TDD/BDD method? is there any dev branch?

**Comment by weotch** [comment]
Thanks for your inquery.  Unfortunately, I didn't follow a test driven approach in developing Decoy. However, I'll be adding integration tests soon as part of adding support for L5.4 ( #6 ).  After that is finished, it should be easier to support collaboration.  I'll keep you posted.

**Comment by lucafregoso** [comment]
Hi @weotch , any news about that?

**Comment by weotch** [comment]
Currently, [the tests we're writing](https://github.com/BKWLD/decoy/tree/master/tests/Integration) are Laravel HTTP tests that are organized by the functionality that is under test.  The [/example](https://github.com/BKWLD/decoy/tree/master/example) directory contains a boilerplate Laravel app that consumes Decoy and whom the http tests are run against.  Much of Decoy was written before we became familiar with dependency injection and adding unit tests to existing features was awkward, thus we went with the http/integration testing approach.  

In the future, and as we add new features, we'll be expanding the test coverage with more http tests as well as unit tests.  If you are adding new features, please make sure it is covered by either http or unit tests.

Please make any PRs against the master branch.

Thanks!
