### ISSUE TITLE
Changing date format throughout Decoy

### ISSUE THREAD

**Issue by tynoesj** [BKWLD/decoy#100]
Where can we change the date format (now American m/d/y) globally?

If not yet implemented, what's the best way to do this? Should be d/m/y everywhere for almost all my applications.

**Comment by weotch** [comment]
You can through the locale.  See the work done for Brazilian Portuguese here: https://github.com/BKWLD/decoy/blob/master/lang/pt_BR/base.php#L5-L7.  I'd welcome you PRing your locale as well.
