### ISSUE TITLE
Possible support of another Theme ?

### ISSUE THREAD

**Issue by minedun6** [BKWLD/decoy#11]
Is there any way we can change the admin template, I'm working with metronic theme, as you know, it's a tricky theme that requires some work on it ?

**Comment by weotch** [comment]
Yeah, I tried to describe this in http://docs.decoy.bukwild.com/views under "Overriding a Decoy partial".  For instance, to change the main layout view, create a view file at `app/views/layouts/default.php`.  Thus, if you needed to TOTALLY overhaul the theme, you would be overriding all the view files.  Furthermore, if you didn't want form elements to be written using Bootstrap-friendly markup, you could put `Former::framework('Nude');` somewhere in your code, that [will tell Former](https://github.com/formers/former/wiki/Features#out-of-the-box-integration-to-bootstrap-and-foundation) to render plainer markup.

Btw, if you have any suggestions about how to make that section of the docs more readable, lemme know.
