### ISSUE TITLE
L5.2.45 Errors when login to admin for first time

### ISSUE THREAD

**Issue by od3n** [BKWLD/decoy#13]
1. Error on `/admin/articles`

```
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined variable: back
```

2. Error on `/admin/elements`

```
fopen(/Users/Od3n/Documents/Git/decoy/public//img/temp/home-marquee.jpg): failed to open stream: No such file or directory (View: /Users/Od3n/Documents/Git/decoy/vendor/bkwld/decoy/views/elements/index.haml)
```

**Comment by seanthepottingshed** [comment]
@od3n Exact same issue in all my admin pages, looks like the server path is incorrect

**Comment by weotch** [comment]
Thanks for the bug reports!

1. Still looking into this one.
2. The elements issue should be fixed now in 5.2.2. Try a composer update.

**Comment by weotch** [comment]
@od3n Do you have php's [short_open_tags](http://php.net/manual/en/ini.core.php#ini.short-open-tag) off?

**Comment by od3n** [comment]
@weotch yes it's off

**Comment by seanthepottingshed** [comment]
@weotch 

> The elements issue should be fixed now in 5.2.2. Try a composer update.

Does this imply that the CMS doesn't work with 5.2.3?

**Comment by weotch** [comment]
@od3n I'll remove the dependency on `short_open_tags` this morning

@seanthepottingshed No, sorry, I meant [Decoy 5.2.2](https://github.com/BKWLD/decoy/releases/tag/5.2.2) fixes that issue.  And, yes, it works with PHP 7.

**Comment by seanthepottingshed** [comment]
@weotch Excellont!

I will give it another crack later on this evening ( GMT ) Looks like a cracking little CMS.

**Comment by weotch** [comment]
@od3n Can you switch your Decoy constraint to `dev-master` and `composer update`?  I pushed up a commit that removes all the short open tags that were being used in a number of views.

**Comment by od3n** [comment]
@weotch it's working fine now, thanks

**Comment by seanthepottingshed** [comment]
@weotch Likewise, all working for me, appreciated.

**Comment by weotch** [comment]
Tagged now as 5.2.3
