### ISSUE TITLE
Add Laravel 5.3 support

### ISSUE THREAD

**Issue by derekbliss** [BKWLD/decoy#14]
First time on login.

"php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "bkwld/decoy": "^5.2"

`FatalErrorException in Login.php line 17:
Trait method hasTooManyLoginAttempts has not been applied, because there are collisions with other trait methods on Bkwld\Decoy\Controllers\Login`

**Comment by weotch** [comment]
Decoy doesn't currently work with Laravel 5.3 but we're currently working on implementing that support.  It should be ready in a week or two.  I'll post back here at that point.  Thanks!

**Comment by derekbliss** [comment]
Awesome thank you!

**Comment by weotch** [comment]
We just added Laravel 5.3 support! 

https://github.com/BKWLD/decoy/releases/tag/5.4.0
