### ISSUE TITLE
Every "save" in model generates a change log for date fields, even when there is no changes in value.

### ISSUE THREAD

**Issue by SomosAMambo** [BKWLD/decoy#20]
Suggestion:

Create a setter mutator for every `protected $dates` in `Base` that checks for changes before committing the model.

E.g.: 
```php
       if ($val) {
           if ($this->attributes[$attr] != $this[$attr]) {
               $this->attributes[$attr] = $val;
           }
       }
```

**Comment by weotch** [comment]
👍  sounds good to me! 

We'll start looking to introduce features like this after we finish adding L5.4 support.

**Comment by weotch** [comment]
@SomosAMambo I can't reproduce this.  If you still can, can you post your edit view?
