### ISSUE TITLE
Example project and docs in separate repo

### ISSUE THREAD

**Issue by Solinx** [BKWLD/decoy#28]
Thanks for sharing this package! I've been looking forward to playing around with it these last few days. Unfortunately I've stumbled across some quirks before completing the quick start steps.

Firstly, could you please separate the example project and the documentation into their own repository? Both the example and the documentation are greatly appreciated, but their inclusion in the Decoy package is causing some problems.

Using PHPStorm I'm now getting warnings all over the place regarding to duplicate classes, resulting from the Laravel example project included in the Decoy package. Unfortunately PHPStorm does not seem to allow me to ignore the folder for autocompletion unless I ignore the entire Decoy package.

Secondly, the size of my project effectively doubled due to the near 30 MB of documentation included in the package. One of the gif assets takes up about 11 MB all by itself. The documentation is certainly valuable and the animation is informative, but doubt it should be part of the production deployment package. It caused a timeout during my initial deployment.

Thanks!

**Comment by brokenhd** [comment]
@Solinx We don't want to remove the example app because its used in the integration tests, but we're thinking of doing this:

http://stackoverflow.com/questions/17049313/how-to-ignore-directories-with-composer

which should solve your issue if you install with `--prefer-dist`. Do you see any issues with that in your use case?

**Comment by Solinx** [comment]
@brokenhd Thanks! That looks like it will work just fine. Could you do the same for the documentation?

**Comment by Solinx** [comment]
Thanks!
