### ISSUE TITLE
Media library?

### ISSUE THREAD

**Issue by Solinx** [BKWLD/decoy#29]
My first impression of the CMS is that's absolutely great. Unfortunately I expect soms resistance during the adoption process in our organisation due to the lack of a media library. Are there any plans for a media/image library? Or would it be easy to create one myself? Thanks!

**Comment by brokenhd** [comment]
It wouldn't be too difficult to implement something like this. The way we are storing images is very friendly to that sort of thing for making an image library. It isn't on our roadmap for now but definitely something we would take a pull request for if you are looking into it!

Here is the one from redactor if you want to take a look: https://imperavi.com/redactor/plugins/imagemanager/

**Comment by Solinx** [comment]
Thanks! Good to know 👍 
Right now we do not have the resources to work on this, but I'm adding it to the backlog.
