### ISSUE TITLE
ErrorException: scandir(C:\Users\emin\Dev\opio\app\Console/Commands,C:\Users\emin\Dev\opio\app\Console/Commands)

### ISSUE THREAD

**Issue by eminos** [BKWLD/decoy#33]
I've just installer Decoy on Laravel 5.4. (I'm really excited about Decoy!!)

I'm getting this error when logging in to the admin:

`Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: scandir(C:\Users\emin\Dev\opio\app\Console/Commands,C:\Users\emin\Dev\opio\app\Console/Commands): The system cannot find the file specified. (code: 2) (View: C:\Users\emin\Dev\opio\vendor\bkwld\decoy\views\layouts\sidebar\_nav.haml) (View: C:\Users\emin\Dev\opio\vendor\bkwld\decoy\views\layouts\sidebar\_nav.haml)`

I'm on Windows, using latest Laragon (Apache, php 7.0).
Could this error be related to the Windows slash/backslash in file paths?
Laravel without Decoy works fine on my system.

**Comment by eminos** [comment]
Actually. I'm missing the Commands folder in /app/Console.
If I create the Commands folder admin seems to work.

**Comment by weotch** [comment]
👍
