### ISSUE TITLE
After upgrading to L5.4 and Decoy dev/master image fields are not working

### ISSUE THREAD

**Issue by SomosAMambo** [BKWLD/decoy#36]
Guys, we are actively searching for the problem since yesterday morning and found nothing so far... so we decided to open an issue. Is it an issue? We are still looking into it.

**Comment by weotch** [comment]
Can you provide more detail on what "not working" means?  Thanks!

**Comment by SomosAMambo** [comment]
Sorry for this. When saving a model from a form with an image field, the validation triggers with the following message (from a dump and die):
```
images.default" => array:1 [
        0 => "Required"
]
```

**Comment by weotch** [comment]
Also related: f7aab6365c0514d212b0c2bf1326486ed3ac04be, b5c26c006e83859bde84aff675d098419062c5d0

@SomosAMambo Can you see if that fixes it?

**Comment by SomosAMambo** [comment]
Everything is good! Thanks!!!
