### ISSUE TITLE
Former::checkbox('category'), Array to string conversion error

### ISSUE THREAD

**Issue by eminos** [BKWLD/decoy#37]
I'm trying to figure out Former::checkbox, following the guide here: http://docs.decoy.bukwild.com/views

This is my view code:
`!= Former::checkbox('category')->checkboxes(Bkwld\Library\Laravel\Former::checkboxArray('category', App\Project::$categories))->push(false)`

The edit page is displayed correctly with the 4 checkboxes from the static array on the App\Project model, but when I try to save I get this:

```Array to string conversion (SQL: update `projects` set `category` = inspiring, `updated_at` = 2017-04-21 18:28:49 where `id` = 1)```

Am I missing something?
What does `->push(false)` mean?

Laravel 5.4, PHP 7.0, MySQL 5.7

**Comment by weotch** [comment]
- [ ] Add checklist to docs
- [ ] Look into single checkbox issue from this ticket

**Comment by weotch** [comment]
I created a `Former::checklist` custom field to make it easier to deal with checkbox lists and updated the docs with it: http://docs.decoy.bukwild.com/custom-fields.  I expect to release a tag with this later tonight.

The missing bit, previously, was this:

---

Note, the checklist field will POST an array to the server.  You can convert this to a string for storing in the database by [casting](https://laravel.com/docs/5.4/eloquent-mutators#array-and-json-casting) to an array:

```php?start_inline=1
// In your model
protected $casts = [
    'category' => 'array',
];
```

... or you can convert to a string by hooking into the saving event, which is easy in Decoy using the `onSaving` no-op method that you inherit by subclassing the Decoy base model.

```php?start_inline=1
// In your model
public function onSaving()
{
    $this->category = implode(',', $this->category);
}
```
