### ISSUE TITLE
Disable "Add new change" 

### ISSUE THREAD

**Issue by noxify** [BKWLD/decoy#40]
Hi,

when filtering the existing changes with something like this:
![bildschirmfoto 2017-04-24 um 21 34 55](https://cloud.githubusercontent.com/assets/521777/25355131/e354899c-2935-11e7-9a2b-0e45ff032b63.png)

I can click on the "New" button... this produces the following:

```
InvalidArgumentException in FileViewFinder.php line 137:
View [changes.edit] not found.
```

I think, to add a change manually makes no sense.

Maybe there is already something like this to disable a "Add new" functionality on a listing.

```
protected $createable = true/false
```

**Comment by weotch** [comment]
> I think, to add a change manually makes no sense.

Agreed, thanks for the report.
