### ISSUE TITLE
Get error on articles listing

### ISSUE THREAD

**Issue by mindmergedesign** [BKWLD/decoy#46]
After following the Quick Start tutorial to create a News Articles Listing, I get the following error when trying to see the list of articles:

```
FatalErrorException in ac61b2b66585f5333939165665079b0553efbf65.php line 0:
Method Bkwld\Decoy\Fields\Listing::__toString() must not throw an exception, caught ErrorException: 
Class 'Article' not found (View: /Users/juan/Sites/completeps/vendor/bkwld/decoy/views/shared/list/_full_header.haml)
```

**Comment by noxify** [comment]
Hi,

i have tested it with a fresh instance (laravel 5.4.20 + decoy 5.6.0) and everything works as excepted.

Only in the `routes/web.php` I had to add `use App\Article;` to remove a similiar problem (now it's just a missing view, which is ok for me)...

But in the backend/admin panel, i got no errors like this.

**Comment by mindmergedesign** [comment]
I deleted the Model and Controller, then I created them again and it worked. I am not really sure what was different.
