### ISSUE TITLE
How to configure the WYSIWYG Editor

### ISSUE THREAD

**Issue by noxify** [BKWLD/decoy#49]
Hi,

is it possible to change the default button configuration from the wysiwyg editor?

I found the default configuration in:
https://github.com/BKWLD/decoy/blob/master/assets/js/wysiwyg/redactor.js#L20

But I didn't found a way to change the buttons.

In the [Custom Fields Documenation](http://docs.decoy.bukwild.com/custom-fields) there is a reference to http://docs.decoy.bukwild.com/wysiwyg but it's a dead link.

Maybe it's possible to use something like this:

```
Former::wysiwyg('body')->buttons(['bold', 'italic', 'link']);
```

or

```
Former::wysiwyg('body')->config(['buttons' => ['bold', 'italic', 'link']]);
```

Or is there already some magic to do this?

Thanks!

**Comment by noxify** [comment]
my bad... http://docs.decoy.bukwild.com/customize

**Comment by noxify** [comment]
I'm not sure what's the problem is, but i have no clue how to extend it.
I copied the code from the docs into the "app.js" (just for testing) but the result after running the webpack script was nothing.

I think it's just a user handling, but maybe you can explain it with one or two sentences :)

**Comment by weotch** [comment]
Eh, it's awkward the way this configuration is handled now.  It's a legacy of before we open-sourced the project and we would compile the js/css as part of the grunt (and later webpack) tooling for the app we were integrating Decoy with.  

Gonna close this as it's the same as #27 but I'll make sure this is part of our next release ... I think we'll have that out htis week.
