### ISSUE TITLE
Visibility toggle not working in list 

### ISSUE THREAD

**Issue by toddvalentine** [BKWLD/decoy#55]
It seems like a Model's public attribute, when getting put through the Bkwld\Library\Utils::nullEmpties is nulling false values. So I am getting the following when attempting to set public to false via the list toggle.

Integrity constraint violation: 1048 Column 'public' cannot be null'

The comments from the nullEmpties method seem to suggest numeric 0 is intentionally being excluded. Is the public boolean getting casted to true/false along the way?

**Comment by noxify** [comment]
@toddvalentine - how did you solved it?

**Comment by toddvalentine** [comment]
I didn't. I closed by mistake. It seems like the visibility toggle returns the error when used from the admin actions in the listing. Toggling visibility from the edit view seems to work fine, so I thought it had been resolved. I will re-open.

**Comment by weotch** [comment]
@toddvalentine what database are you using?  We [have tests](https://github.com/BKWLD/decoy/blob/master/tests/Integration/ListingTest.php#L57-L93) so it's working properly in sqlite and in our /example app:

![](http://yo.bkwld.com/3f1t3m2m362k/Screen%20Recording%202017-05-05%20at%2008.50%20AM.gif)

**Comment by toddvalentine** [comment]
@weotch mysql.  

<img width="1243" alt="screen shot 2017-05-05 at 4 52 11 pm" src="https://cloud.githubusercontent.com/assets/367941/25765598/6cc81182-31b3-11e7-85aa-d38e77bd9594.png">

**Comment by weotch** [comment]
Huh, and Travis is testing against both PHP 5.6 and 7 on this too.  @noxify are you having this issue too?  Trying to figure out how to recreate locally.

**Comment by noxify** [comment]
Didn't noticed something like this.

But would be good to see the preview from the failed ajax request.

But i will give it a try this evening (saturday to sunday).

Which MySQL Version are you using?
I tested it only with 5.6.

**Comment by toddvalentine** [comment]
I'm on MariaDB: Server version: 10.0.28-MariaDB-0+deb8u1 (Debian)

![screen shot 2017-05-06 at 8 38 06 am](https://cloud.githubusercontent.com/assets/367941/25772759/62d1aef2-3237-11e7-94b0-8bdd923c2191.png)

**Comment by noxify** [comment]
### Laravel Environment

- Laravel Version: 5.4.21
 - Timezone: UTC
 - Debug Mode: ✔
 - Storage Dir Writable: ✔
 - Cache Dir Writable: ✔
 - Decomposer Version: ^1.2
 - App Size: 38 MB
 
 ### Server Environment

 - PHP Version: 7.0.15
 - Server Software: Apache
 - Server OS: Darwin Marcuss-MBP.fritz.box 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
 - Database: pgsql 9.6.1.0 / mysql 5.6.35
 - SSL Installed: ✘
 - Cache Driver: file
 - Session Driver: file
 - Openssl Ext: ✔
 - PDO Ext: ✔
 - Mbstring Ext: ✔
 - Tokenizer Ext: ✔
 - XML Ext: ✔
 
 ### Installed Packages & their version numbers

 - bkwld/decoy : ^5.6
 - laravel/framework : 5.4.*
 - laravel/tinker : ~1.0
 - lubusin/laravel-decomposer : ^1.2

----

I tested it with a fresh installation together with the stuff from the existing example.
I had the same result with postgres as with mysql as @weotch.

It seems, that it's "only" an mariadb specific problem.

**Comment by noxify** [comment]
Maybe you can modify the migration file from:

```
            $table->boolean('public');
```

to:

```
            $table->boolean('public')->nullable();
```

**Comment by toddvalentine** [comment]
I will try this and close. Thanks.
