### ISSUE TITLE
Assets on S3

### ISSUE THREAD

**Issue by mindmergedesign** [BKWLD/decoy#56]
I am planning to store all my app's assets on S3 and not on the local filesystem. I made my default filesystem S3 in the filesystems.php config file; however, when I upload a file for a post, etc, it is still saved on my local storage folder and not on my designated S3 folder. Am I missing something? or S3 is not supported for assets.

**Comment by weotch** [comment]
Decoy uses our [Upchuck](https://github.com/BKWLD/upchuck) package to store files.  To store on S3, [publish it's config file](https://github.com/BKWLD/upchuck#installation) and then edit it to use an S3 disk.  The [comments in the config file](https://github.com/BKWLD/upchuck/blob/master/config/config.php) hopefully explain this well enough.
