### ISSUE TITLE
Question: Create related model from parent model view?

### ISSUE THREAD

**Issue by eminos** [BKWLD/decoy#59]
I'm still learning Decoy. I love it, but the documentation is really lacking a lot of info/tutorials which makes it really hard to accomplish what I have in mind and also a lot of trial and error.

Anyway, my question is:

I have a model called Service. Each Service can haveMany Boxes (limited to max 3). How would I create those boxes from the Service edit view in admin?

Also (and this is probably related), I know how to add images to a model, and you can name the image in the view Former helper. But how would I add an "iterable images field". To create separate image fields for 10s or hundreds of images seems wrong. I would, of course, like to add/upload those images on the actual parent model edit view and not a separate admin page for "images" (or "boxes" for the previous example with Service hasMany Box).

Yet another question is: is there a way to create a sortable related model field. I can see both autocomplete fields and related model checkboxes, but is there a field type where one could select a bunch of related stuff and then order them (drag drop)?

I hope you guys can push me in the right direction. (I will probably have more questions like this soon)

**Comment by eminos** [comment]
I guess what I'm asking for is how to make something like the first screenshot on this page:
http://www.bukwild.com/article/introducing-decoy
Where you can add items (Visuals) from the view page of the parent (Project).

**Comment by eminos** [comment]
Hmm. I think I figured it out! It's just a regular Laravel related model. And then you add it to the sidebar in the view. Seems to work fine!

**Comment by mindmergedesign** [comment]
@eminos would you mind sharing your Model and view files. I am trying to load related tags to my view but I haven't been able to do it. Thank you

**Comment by eminos** [comment]
In the model I just created a normal Laravel relationship:

```php
//  App\Service
public function boxes()
    {
        return $this->hasMany('App\Box');
    }

// App\Box
public function service()
    {
        return $this->belongsTo('App\Service');
    }
```

And in the services/edit.haml.php:

```haml
- $sidebar->add(Former::listing('App\Box'))
```

**Comment by mindmergedesign** [comment]
I am doing the same bu with a belongsToMany relationship and it is not working.
```
// App\Recipe
public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

// App\Tag
public function recipes()
    {
        return $this->belongsToMany(Recipe::class);
    }

```
I am not sure what I am doing wrong.

**Comment by eminos** [comment]
Shouldn't it be `hasMany` on the `tags()` method?
I'm pretty new at Laravel as well, so I'm not the best person to try to help you :)
Check the Laravel docs?

**Comment by mindmergedesign** [comment]
@eminos I followed a tutorial from Laracasts about adding tags and that's how Jeffrey Way explained it. If Jeffrey Ways says is like that, it must be true :-)

**Comment by mindmergedesign** [comment]
@eminos I figured it out. I was passing the Recipe model in the view instead of the Tag model

```
// Before
- $sidebar->add(Former::listing('App\Recipe'))

/ After
- $sidebar->add(Former::listing('App\Tag'))

```

**Comment by weotch** [comment]
Sounds like you'e figured it out but, yeah, the _main_ objective of Decoy was being a CMS that worked with Eloquent models.  So you create Eloquent relationships and Decoy provides a number of special fields for interacting with those relations. 

> Yet another question is: is there a way to create a sortable related model field. I can see both autocomplete fields and related model checkboxes, but is there a field type where one could select a bunch of related stuff and then order them (drag drop)?

If it's a one to many relation, you need to have a `position` column on the child table.  See [this](https://github.com/BKWLD/decoy/blob/master/docs/models.md#drag-and-drop) for some info on automatically setting the initial position value to be at the end of the list.  If it's a many to many, you put the `position` column on the pivot table.  See [this](https://github.com/BKWLD/decoy/blob/master/docs/models.md#many-to-many-relationships) for some info on setting the initial value on the pivot table.
