### ISSUE TITLE
Add Laravel 5.4 support

### ISSUE THREAD

**Issue by weotch** [BKWLD/decoy#6]
Trust to the `ConvertEmptyStringsToNull` middleware to converty empty string to null rather than that PHP Library method.

**Comment by jonathan-bird** [comment]
+1 - when can we expect a 5.4 release?

**Comment by weotch** [comment]
I hope to in the next couple of weeks.  Though I could see bumping it up if there is a lot of demand for it.

**Comment by jonathan-bird** [comment]
It'd definitely be great, I want to use it on a project that's due in a couple weeks.

**Comment by symfonycoda** [comment]
This looks awesome. I'll give it a go when the 5.4 version is up. Unfortunately I don't have time to contribute with code, but i m happy to help with trying it out and giving feedback/finding errors if that helps?

**Comment by weotch** [comment]
That would be great, thanks for the offer.  It's looking good for me to break ground on this feature this week.

Btw, my first step will be to add integration tests for the current version and then see what breaks when updating the Laravel version constaint.

**Comment by jonathan-bird** [comment]
Very excited!

**Comment by Solinx** [comment]
+1

**Comment by eminos** [comment]
+1

**Comment by weotch** [comment]
To update this thread, we've finished the integration test phase, next step will be adding 5.3 support and then immediately on to 5.4.

**Comment by eminos** [comment]
@weotch I hate asking, but do you have an idea of when 5.4 compatibility might be ready? Days, weeks months? I'm starting a new website project this week and would love to try using Decoy for it, but using the old L5.2 for it just to be able to use Decoy feels a bit backwards :)

**Comment by weotch** [comment]
I would say within 2 weeks from now, ideally this week.

**Comment by weotch** [comment]
It's out! https://github.com/BKWLD/decoy/releases/tag/5.5.0

**Comment by jonathan-bird** [comment]
Awesome, cheers!
