### ISSUE TITLE
Validation rules are not working

### ISSUE THREAD

**Issue by mindmergedesign** [BKWLD/decoy#61]
I get an error when creating new entries in any of my models.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'body' cannot be null ...
``` 
No field can be left empty/null. I have tried to add validation rules for each field and mark it as nullable as follows:

```
public static $rules = [
        'title' => 'required',
        'water' => 'string|nullable',
        'body' => 'nullable',
        'slug' => 'alpha_dash|unique:meal-plans',
        'date' => 'required',
        'url' => 'url',
     ];
```

Even though I mark some of the fields as nullable, I still get the Integrity constraint violation error. Only the required rule is accepted.

**Comment by weotch** [comment]
It sounds to me like your database isn't allowing `null` for the `body` field.  Can you paste your migration here?

**Comment by mindmergedesign** [comment]
@weotch here is a sample migration:

```
public function up()
    {
        Schema::create('meal_plans', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->string('slug')->unique();
            $table->string('water');
            $table->text('breakfast');
            $table->text('mid_morning');
            $table->text('lunch');
            $table->text('mid_afternoon');
            $table->text('dinner');
            $table->text('after_dinner');
            $table->text('resources');
            $table->integer('user_id');
            $table->date('date');
            $table->boolean('public')->default(1);
            $table->timestamps();
            $table->index(['public', 'date']);
            $table->integer('position');
        });
    }
```

**Comment by weotch** [comment]
None of those are `->nullable()`.  Try setting the ones that are failing to that.

**Comment by mindmergedesign** [comment]
@weotch Yes, that did the trick. I made the changes in the migration and it works. However, I was under the impression that I could do that also from the rules validation in the model.

**Comment by eminos** [comment]
@mindmergedesign You can do it in the rules validation, but if no fields are nullable() in the DB then all of them need to be required in the validation (not just some fields). Not nullable() + empty field = error.

**Comment by mindmergedesign** [comment]
@eminos Thank you for the clarification.
