### ISSUE TITLE
JPG vs jpg

### ISSUE THREAD

**Issue by Solinx** [BKWLD/decoy#62]
Thanks for open sourcing this CMS. We're using it to make our makeshift website at www.duurzameweek.nl manageable by our volunteers. 

Yesterday I got a support call about uploading images. Uploading worked fine and the image showed up in the back end, but not on the actual website. Turns out the image had uppercase JPG as extension, and changing that to lowercase solved the issue (file & DB entry). 

As far as I can tell this is something I cannot fix at the front-end. Could you look into it? Thanks!

**Comment by weotch** [comment]
Were they being uploaded into a model or into Elements?

**Comment by Solinx** [comment]
models

**Comment by weotch** [comment]
I can't recreate an issue with caps.  Maybe it was something else with the image?  Can you send me the image that was causing issues?

**Comment by Solinx** [comment]
It was this image that caused problems: [link](http://duurzameweek.nl/uploads/06/00/Groen_leesvoer.1494429223.jpg)
Only initially instead of having a `.jpg` extension it had `.JPG` as extension. 

Uploading the image worked fine with the uppercase extension. It was stored just fine with uppercase extension, both in the filesystem and in the database. And it also displayed fine in the admin panel. 

Only it did not display on the actual website, where I simply used `{{ $model->img()->url }}` within a blade template. 

I 'fixed' the issue by simply renaming the file in the filesystem and updating the database entry. It's the exact same image and no code was altered. Only the extension was changed from uppercase to lowercase.

**Comment by weotch** [comment]
I still can't reproduce it, when I run `$model->img()->url`, I get the URL: `http://decoy.dev/uploads/15/15/Groen_leesvoer.1494429223.JPG` which should be roughly similar to what you are outputting; no issue.  Maybe something on your webserver is the issue.  What is the exact error that is happening?

**Comment by Solinx** [comment]
Hmmm... Tomorrow in the afternoon I'll be working on the website again. I'll do some tests on the server.
