### ISSUE TITLE
Disable nl2br() on textbox, for use with json

### ISSUE THREAD

**Issue by eminos** [BKWLD/decoy#65]
Is there a way to disable the nl2br() on textboxes? I'm using a textbox (Element) to manage a json string, and it get's broken by nl2br().

**Comment by weotch** [comment]
Yeah, if you do `Decoy::el('path.to.element')->value` it will get the raw value for the element.  Those transformations happen when `value()` is called by `__toString()`: https://github.com/BKWLD/decoy/blob/master/classes/Models/Element.php#L120-L144
