### ISSUE TITLE
Adopt PSR-1 & 2

### ISSUE THREAD

**Issue by svenluijten** [BKWLD/decoy#7]
Hey! I was wondering if there is any interest in switching this codebase to adopt some de-factor PHP standards (mainly [PSR-2](http://www.php-fig.org/psr/psr-2/), thus including [PSR-1](http://www.php-fig.org/psr/psr-1/)). 

I can work on porting the codebase over if you want, but I'd like your opinions on this before I get to work 🙂

**Comment by weotch** [comment]
After some internal hemming and hawing, yeah, I'm open to it and I really appreciate the offer.  If you PR it, I'll merge it in.

I'm gonna close this as a result.
