### ISSUE TITLE
wysiwyg editor trying to customise

### ISSUE THREAD

**Issue by georgejkollias** [BKWLD/decoy#94]
Hi, 

how can you just simply add a blockquote to the wysiwyg editor

cheers
George

**Comment by tynoesj** [comment]
Also, any chance of bringing back the page?

http://docs.decoy.bukwild.com/wysiwyg seems to be offline.

**Comment by weotch** [comment]
The docs on the wysiwyg were moved into http://docs.decoy.bukwild.com/customize.  

@georgejkollias by adding `formatting: ['p', 'h2', 'h3', 'blockquote']` like you can see on that page, you can add a `blockquote`.

**Comment by georgejkollias** [comment]
Still cant figure out how to customise this wysiwyg editor.

what is the actual file that you update?

http://docs.decoy.bukwild.com/customize

says you have to edit the Redactor config.

My question is where to you edit it so you can add 

formatting: ['p', 'h2', 'h3', 'blockquote']

i have tried to add my own JS file but the editor no longer functions.

regards
George
