### ISSUE TITLE
Images + Files WYSIWYG editor

### ISSUE THREAD

**Issue by georgejkollias** [BKWLD/decoy#98]
Hi

With the editor, by default why don't the image and file tab appear?

buttons:["bold","italic","link","image","file","horizontalrule","orderedlist","unorderedlist","html"]

is there something you have to configure for the ability to be able to upload images or files in the editor?

**Comment by codivist** [comment]
You can customize the wysiwyg options following the instructions here: http://docs.decoy.bukwild.com/customize
